# Generated by Django 5.0.6 on 2024-06-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seismicdataforexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.CharField(max_length=255, verbose_name='BLOCK')),
                ('usi_code', models.CharField(max_length=255, verbose_name='USI_CODE')),
                ('region', models.CharField(max_length=255, verbose_name='REGION')),
                ('length_km', models.DecimalField(decimal_places=6, max_digits=6, verbose_name='LENGTH_KM')),
                ('acquisition_year', models.IntegerField(verbose_name='ACQUISITION_YEAR')),
                ('processing_year', models.IntegerField(verbose_name='PROCESSING_YEAR')),
            ],
        ),
    ]
