# Generated by Django 5.0.6 on 2024-06-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_seismicdataforexam_length_km'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seismicdataforexam',
            old_name='blocks',
            new_name='block',
        ),
    ]
